### ISSUE TITLE
Changing the name of the file

### ISSUE THREAD

**Issue by eneskemalergin** [whoislimos/Python-Codes#1]
Hey Halim,  I came across to your repository, 

I think you should consider to change the name of files ending with .py :)

**Comment by whoislimos** [comment]
lol uh oh, I don't follow. Which one exactly?

**Comment by eneskemalergin** [comment]
They all txt format or formatless, you should change the code files into .py files which is python file extension

**Comment by whoislimos** [comment]
I just renamed the bubble sort to Bubble_sort.py, is that all I actually needed to do?

**Comment by eneskemalergin** [comment]
Exactly that is the thing :) 

Now Change everything so people can say they are python code :100: % 

Good Luck...

**Comment by whoislimos** [comment]
Wow thanks a bunch!
